version: '3'

services:

      app:
         build: 
           context: ./ltms_project1
         image: idas-django:v1.0
         container_name: idas-web
         restart: unless-stopped
         ports:
            - "8000:8000"
         volumes:
            - "./ltms_project1/ltms_project1/settings.py:/app/ltms_project1/ltms_project1/settings.py"
         depends_on: 
            - db
            - web
        
         command: " bash -c 'python manage.py makemigrations &&
                             python manage.py migrate &&
                             gunicorn ltms_project1.wsgi -b 0.0.0.0:8000'"
      
      db:
        image: postgres
        container_name: idas-db
        volumes:
          - pgdata:/var/lib/postgres/data/
        environment:
          - POSTGRES_PASSWORD=secret
        ports:
          - "5432"

      web:
         # build:
         #    context: ./apache
         image: httpd:2
         #idas-webserver
         container_name: idas-ws
         ports:
            - "80:80"
volumes:
   pgdata:
#   webapp:
